### ISSUE TITLE
VPS ERROR: <aiohttp.connector.TCPConnector object at 0x7f56e0757110>

### ISSUE THREAD

**Issue by DavidAI2024** [vsakkas/sydney.py#156]
I know that maybe it's not a Sydney-py error but I'm going crazy, I can't understand why if I start the Sydney-py example script locally it works, as soon as I start the VPS (Ovh Cloud) I get this errore. `Traceback (most recent call last):
  File "/home/ubuntu/pp.py", line 24, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/pp.py", line 8, in main
    async with SydneyClient() as sydney:
  File "/home/ubuntu/.local/lib/python3.11/site-packages/sydney/sydney.py", line 94, in __aenter__
    await self.start_conversation()
  File "/home/ubuntu/.local/lib/python3.11/site-packages/sydney/sydney.py", line 444, in start_conversation
    response_dict = await response.json()
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1166, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://copilot.microsoft.com/turing/conversation/create?bundleVersion=1.1573.2')
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f56e0757090>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f56e0902a50>, 1195.864796355)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f56e0757110>`

**Comment by DavidAI2024** [comment]
Thanks so much for your help if you can 💕 @vsakkas
