### ISSUE TITLE
<_overlapped.Overlapped object at 0x000002430C626430> still has pending operation at deallocation, the process may crash  

### ISSUE THREAD

**Issue by abinjob** [vsakkas/sydney.py#83]
You: 你好
Sydney: Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000002430C626430> still has pending operation at deallocation, the process may crash  
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000002430C626430> still has pending operation at deallocation, the process may crash  
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000002430C626430> still has pending operation at deallocation, the process may crash

**Comment by abinjob** [comment]
import asyncio
from sydney import SydneyClient

BING_COOKIE = '1bZMhNoRSHVsRB5ZxQXxy1TYbKxS3Ma4XNTgliR0V-JTG1o2yVaNXWbEu0vwfWtxOBkoRLMkoOSSaWFTNOiOQFgNAQY24aI2PgVjdJY_-NATsn56mK7aHXeHHl851ePSZL0UNX4m2zhY5qzXWGx5krS8-OitG9RDb_9NxI3l3hr4Wec-gG_mz3vdruI7jeytCZkOO0npdz1nU505f6Zdedg' # or set it to anything if you don't want to use cookies!



async def main() -> None:
    async with SydneyClient(bing_u_cookie=BING_COOKIE) as sydney:
        while True:
            prompt = input("You: ")

            if prompt == "!reset":
                await sydney.reset_conversation()
                continue
            elif prompt == "!exit":
                break

            print("Sydney: ", end="", flush=True)
            async for response in sydney.ask_stream(prompt):
                print(response, end="", flush=True)
            print("\n")


if __name__ == "__main__":
    asyncio.run(main())

**Comment by abinjob** [comment]
`import asyncio
from sydney import SydneyClient

os.environ["BING_U_COOKIE"] = "1bZMhNoRSHVsRB5ZxQXxy1TYbKxS3Ma4XNTgliR0V-JTG1o2yVaNXWbEu0vwfWtxOBkoRLMkoOSSaWFTNOiOQFgNAQY24aI2PgVjdJY_-NATsn56mK7aHXeHHl851ePSZL0UNX4m2zhY5qzXWGx5krS8-OitG9RDb_9NxI3l3hr4Wec-gG_mz3vdruI7jeytCZkOO0npdz1nU505f6Zdedg"
BING_COOKIE = '1bZMhNoRSHVsRB5ZxQXxy1TYbKxS3Ma4XNTgliR0V-JTG1o2yVaNXWbEu0vwfWtxOBkoRLMkoOSSaWFTNOiOQFgNAQY24aI2PgVjdJY_-NATsn56mK7aHXeHHl851ePSZL0UNX4m2zhY5qzXWGx5krS8-OitG9RDb_9NxI3l3hr4Wec-gG_mz3vdruI7jeytCZkOO0npdz1nU505f6Zdedg' # or set it to anything if you don't want to use cookies!



async def main() -> None:
    async with SydneyClient(bing_u_cookie=BING_COOKIE) as sydney:
        while True:
            prompt = input("You: ")

            if prompt == "!reset":
                await sydney.reset_conversation()
                continue
            elif prompt == "!exit":
                break

            print("Sydney: ", end="", flush=True)
            async for response in sydney.ask_stream(prompt):
                print(response, end="", flush=True)
            print("\n")


if __name__ == "__main__":
    asyncio.run(main())`

**Comment by abinjob** [comment]
import asyncio
from sydney import SydneyClient

BING_COOKIE = '1bZMhNoRSHVsRB5ZxQXxy1TYbKxS3Ma4XNTgliR0V-JTG1o2yVaNXWbEu0vwfWtxOBkoRLMkoOSSaWFTNOiOQFgNAQY24aI2PgVjdJY_-NATsn56mK7aHXeHHl851ePSZL0UNX4m2zhY5qzXWGx5krS8-OitG9RDb_9NxI3l3hr4Wec-gG_mz3vdruI7jeytCZkOO0npdz1nU505f6Zdedg' # or set it to anything if you don't want to use cookies!
async def main() -> None:
    async with SydneyClient(bing_u_cookie=BING_COOKIE) as sydney:
        while True:
            prompt = input("You: ")
            if prompt == "!reset":
                await sydney.reset_conversation()
                continue
            elif prompt == "!exit":
                break
            print("Sydney: ", end="", flush=True)
            async for response in sydney.ask_stream(prompt):
                print(response, end="", flush=True)
            print("\n")
if __name__ == "__main__":
    asyncio.run(main())

**Comment by abinjob** [comment]
>if platform.system() == 'Windows':
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())


You: 给我一个笑话
Sydney: Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site
















                                                                                                                                       e-packages\websockets\legacy\client.py", line 662, in __await_impl__
    await protocol.handshake(
  File "C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\websockets\legacy\client.py", line 329, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\websockets\legacy\client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
  File "C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\websockets\legacy\client.py", line 676, in __await_impl__
    await protocol.wait_closed()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\sydney.py-master\sydney.py-master\tests\testSydeny.py", line 31, in <module>
    asyncio.run(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "d:\sydney.py-master\sydney.py-master\tests\testSydeny.py", line 25, in main
    async for response in sydney.ask_stream(prompt):
  File "C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sydney\sydney.py", line 511, in ask_stream
    async for response, suggested_responses in self._ask(
  File "C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sydney\sydney.py", line 308, in _ask
    self.wss_client = await websockets.connect(
  File "C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\websockets\legacy\client.py", line 654, in __await_impl_timeout__
    async with asyncio_timeout(self.open_timeout):
  File "C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\websockets\legacy\async_timeout.py", line 169, in __aexit__
    self._do_exit(exc_type)
  File "C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\websockets\legacy\async_timeout.py", line 252, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
